auth:
  key     : a919ae5378334f20b8db4f7610cdd1a7
  secret  : 7dff49aab9dc91cb62a0fd34bf9e8c2d6eb3b207
  duration: 1800      # 30 minute validity period for signed upload forms

templates:
  potopolio_store_image : '17bbce134dcf4d80aea8a468c55f7baa'